# This Dockerfile is used to cross-build the kubectl-oadp binaries for all platforms
# It also builds a Go server that serves the binaries for download

FROM --platform=$BUILDPLATFORM golang:1.24 AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN make release-archives && \
    mkdir -p /archives && \
    mv *.tar.gz /archives/

# Build the download server for the TARGET platform (the arch this container will run on)
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o download-server ./cmd/downloads/server.go

# Clean up to reduce layer size
RUN go clean -cache -modcache -testcache && \
    rm -rf /root/.cache/go-build && \
    rm -rf /go/pkg

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

# Only copy compressed tarballs (much smaller than raw binaries)
COPY --from=builder /archives /archives

# Copy the download server
COPY --from=builder /app/download-server /usr/local/bin/download-server

EXPOSE 8080

CMD ["/usr/local/bin/download-server"]
